name: Release queue
on:
  workflow_dispatch: {}
  issue_comment:
    types: [created]
  pull_request_target:
    branches: [main, next-minor, next-major]
  push:
    branches: [main, next-minor, next-major]

permissions: {}

jobs:
  update:
    if: github.repository_owner == 'evryg-org'
    name: Update
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.EVRYG_BOT_GH }}
      - run: gh pr checkout ${{ github.event.pull_request.number }}
        if: github.event.pull_request
        env:
          GITHUB_TOKEN: ${{ secrets.EVRYG_BOT_GH }}
      - uses: tim-smart/next-release-action@main
        with:
          github_token: ${{ secrets.EVRYG_BOT_GH }}
          packages: "@evryg/demo"
